version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/usr/src/app
    command: sh -c "cd front-end && yarn start"
    ports:
     - "3000:3000"
    tty: true
